### ISSUE TITLE
Livecode

### ISSUE THREAD

**Issue by daelfer** [petersimonsson/libqatemcontrol#13]
Is there any way of connecting and controling the ATEM with livecode?

**Comment by petersimonsson** [comment]
Hi,
I have never used livecode but if it can interface with a c++ library you should be able to use the offical api on windows and mac at least... You could also write a livecode native lib of your own by using the protocol documentation available here: http://skaarhoj.com/fileadmin/BMDPROTOCOL.html

**Comment by daelfer** [comment]
I wouldnt mind building a library in livecode of simple things if i knew exactly how to do that. Usually with livecode i open a socket to an IP address with port number to communicate with other devices then send commands to that socket. But im what protocols i should be sending from the shaarhoj document.
