### ISSUE TITLE
USB h264 Mts Stream

### ISSUE THREAD

**Issue by offtools** [petersimonsson/libqatemcontrol#14]
Hello,

is there a plan to support capturing the USB h264 Stream of the TVS under Linux with libqatem, unfortunatly the Blackmagic SDK under Linux doesnt support it.

Thanks offtools.

**Comment by petersimonsson** [comment]
Hi,
Sorry for the late reply...
No there's no plan to support the USB protocols. I'll leave that as an exercise for someone using it.

// Peter Simonsson
