### ISSUE TITLE
Compile on OSX

### ISSUE THREAD

**Issue by metropt** [petersimonsson/libqatemcontrol#22]
I tried to build your library on OSX. I successfully build and install it.
Now I'm having problems with the example. I tried to build and it says it can't find the header files so I copy the header files inside the example project: 
http://pastebin.com/kcAuwzr7

But now it keep giving me the following error:
http://pastebin.com/pvbHxuxX

Thank you

**Comment by petersimonsson** [comment]
Sorry, I forgot to update the example after I changed the API a bit. :(
Will have a look at fixing it tomorrow.

**Comment by metropt** [comment]
Great :) thank you!

**Comment by brunini** [comment]
I can't build the example on linux too. Errors like "mainwindow.cpp:298:23: error: ‘class QAtemConnection’ has no member named ‘doDownstreamKeyAuto’"

**Comment by petersimonsson** [comment]
The qatemswitcher example has now been updated for the new downstreamkey API. So hopefully everything works for you now.

**Comment by metropt** [comment]
it works now, thank you.

PS: I got some segmentation faults as soon as I started to use the library I'll try to identify where they come and tell you.
