### ISSUE TITLE
upstreamKeyType (m_type value) not work

### ISSUE THREAD

**Issue by rem5** [petersimonsson/libqatemcontrol#23]
Hi,

Based on the qatemswitcher example, I successfully set parameters for a chroma key on the first upstreamkey in the mainwindow.cpp:

```
    m_atemConnection->mixEffect(0)->setUpstreamKeyFillSource(0, 2);
    m_atemConnection->mixEffect(0)->setUpstreamKeyChromaHue(0,175.7);
    m_atemConnection->mixEffect(0)->setUpstreamKeyChromaGain(0,100.0);
    m_atemConnection->mixEffect(0)->setUpstreamKeyChromaYSuppress(0,63.3);
```

All of this is automatically set to my ATEM Television Studio.

But to set the chroma key type:
`    m_atemConnection->mixEffect(0)->setUpstreamKeyType(0, 1);`
It not works, it stays on the current key type selected in the ATEM Software Control application of BlackMagicDesign).
(http://skaarhoj.com/fileadmin/BMDPROTOCOL.html)

Tried also to show the value of m_type via a new get function but returns empty value:
std::cout << m_atemConnection->mixEffect(0)->getUpstreamKeyType(0);

```
quint8 QAtemMixEffect::getUpstreamKeyType(quint8 keyer)
{
    return m_upstreamKeys[keyer]->m_type;
}
```
in qatemmixeffect.cpp, and signature in qatemmixeffect.h

Can you reproduce the problem ?

Maybe a wrong payload message ?

Thanks for your ideas...

**Comment by petersimonsson** [comment]
I probably won't have time to look into this until next week, but which version are you using? My guess is that the protocol has changed since I last checked that functionality.

**Comment by rem5** [comment]
Hi Peter,

Thanks for your answer
I use ATEM Software Control version 6.9.
Is it this version number you need or another reference ?
Maybe can I check it if you have a link to know how to check the packet sent via the protocol ?

**Comment by petersimonsson** [comment]
Thanks that was the version number I was after.

**Comment by petersimonsson** [comment]
Ok so BM decided to change the size of the command for some reason. Everything else was the same so master should work for you now.
